---
- hosts: localhost
  connection: local
  become: true
  roles:
    - role: python3
    - role: remove-initial-setup
      vars:
        user: "wouter"
    - role: disable-upgrade
      vars:
        user: "wouter"
    - role: adm-users
      vars:
        user: "wouter"
        password: "$6$i2Tj/l3o5rH2XQDr$EXbxoUdukY4x8mjR2OUz4f53lU9EGk6xh9fvJomNZllsgIjJyrFkFoT2Lq2k3qsPiDea9jOZ7ZMDP1w3MjJ8p/"
        fullname: "Wouter Spaans"
    - role: autologon
      vars:
        user: "wouter"
    - role: dotnet-sdk-5.0
    - role: vscode
      vars:
        become_user: "wouter"
