- name: Add the user '{{user}}' with a specific uid and a primary group of 'adm'
  ansible.builtin.user:
    name: "{{user}}"
    shell: /bin/bash
    comment: "{{fullname}}"
    groups:
      - adm
      - cdrom
      - sudo
      - dip
      - plugdev
      - lxd
    password: "{{password}}"
